services:
  # metricraft:
  #   image: damianek952/metricraft:latest
  #   environment:
  #     APPNAME: ${APPNAME:-my-app}
  #     DEST_PORT: ${DEST_PORT:-3000}
  #     NUXT_PUBLIC_HTTPHOST: ${METRICRAFT_PUBLIC_URL:-http://localhost:8080}
  #     NUXT_PUBLIC_WSSHOST: ${METRICRAFT_WS_URL:-ws://localhost:8080}
  #   ports:
  #     - 8000:8000
  #     - 8080:8080
  #     - 8081:8081
  #   volumes:
  #     - metricraft-db:/var/lib/postgresql/data
  #   networks:
  #     - metricraft-network
  postgresql:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
    networks:
      - metricraft-network
    restart: no
  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql
    networks:
      - metricraft-network
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - metricraft-network
    restart: always
networks:
  metricraft-network:
    driver: bridge
volumes:
  metricraft-db:
  postgresql:
  pgadmin:
