services:
  postgresql:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - postgresql:/var/lib/postgresql/data
    networks:
      - metricraft-network
    restart: no
  metricraft:
    build: ./metricraft
    ports:
      - 8000:8000
    networks:
      - metricraft-network
    depends_on:
      - postgresql

  backend:
    build: ./backend
    ports:
      - 8080:8080
    networks:
      - metricraft-network
    depends_on:
      - postgresql
  worker:
    build: ./worker
    ports:
      - 8081:8081
    networks:
      - metricraft-network
    depends_on:
      - postgresql
  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    # volumes:
    #   - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - metricraft-network
    restart: always
networks:
  metricraft-network:
    driver: bridge
