services:
  postgresql:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - metricraft-network
    restart: no

  redis:
    image: redis:latest
    networks:
      - metricraft-network
    restart: always

  backend:
    build:
      context: ./backend
      args:
        SECRET: ${SECRET}
        APPNAME: ${APPNAME}
        ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
        DATABASE_USERS: ${DATABASE_USERS}
        DATABASE_LOGS: ${DATABASE_LOGS}
    ports:
      - "8080:8080"
    networks:
      - metricraft-network
    depends_on:
      - postgresql
      - redis

  worker:
    build:
      context: ./worker
      args:
        SECRET: ${SECRET}
        APPNAME: ${APPNAME}
        DATABASE_LOGS: ${DATABASE_LOGS}
    ports:
      - "8081:8081"
    networks:
      - metricraft-network
    depends_on:
      - postgresql

  metricraft:
    build:
      context: ./metricraft
      args:
        SECRET: ${SECRET}
        APPNAME: ${APPNAME}
        DOMAIN: ${DOMAIN}
    ports:
      - "80:8000"
    networks:
      - metricraft-network
    depends_on:
      - postgresql
      - redis
      - backend
      - worker
networks:
  metricraft-network:
    driver: bridge
volumes:
  postgresql:
  pgadmin:
