services:
  postgresql:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - metricraft-network
    restart: no
  redis:
    image: redis:latest
    networks:
      - metricraft-network
    restart: always

  backend:
    build:
      context: ./backend
      args:
        SECRET: ${SECRET}
        APPNAME: ${APPNAME}
        ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
        DATABASE_USERS: ${DATABASE_USERS}
        GOOGLE_APP_PASSWORD: ${GOOGLE_APP_PASSWORD}
    environment:
      MODE: docker
      DATABASE_LOGS: postgresql://postgres:password@postgresql:5432/postgres?sslmode=disable
    expose:
      - "8080"
    networks:
      - metricraft-network
    depends_on:
      - postgresql
      - redis

  worker:
    build:
      context: ./worker
      args:
        SECRET: ${SECRET}
        APPNAME: ${APPNAME}
    environment:
      MODE: docker
      DATABASE_LOGS: postgresql://postgres:password@postgresql:5432/postgres?sslmode=disable
      DEST_PORT: ${DEST_PORT:-3000}
    expose:
      - "8081"
    networks:
      - metricraft-network
    depends_on:
      - postgresql

  metricraft:
    build:
      context: ./metricraft
      args:
        SECRET: ${SECRET}
        APPNAME: ${APPNAME}
        DOMAIN: ${DOMAIN}
    expose:
      - "8000"
    networks:
      - metricraft-network
    depends_on:
      - postgresql
      - redis
      - backend
      - worker

  reverse-proxy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - metricraft-network
    depends_on:
      - metricraft
      - backend
      - worker

networks:
  metricraft-network:
    driver: bridge
volumes:
  postgresql:
  pgadmin:
