// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timeframe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Resolution    int32                  `protobuf:"varint,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timeframe) Reset() {
	*x = Timeframe{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timeframe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeframe) ProtoMessage() {}

func (x *Timeframe) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeframe.ProtoReflect.Descriptor instead.
func (*Timeframe) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Timeframe) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Timeframe) GetResolution() int32 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

type StringInt32Map struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]int32       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringInt32Map) Reset() {
	*x = StringInt32Map{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringInt32Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringInt32Map) ProtoMessage() {}

func (x *StringInt32Map) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringInt32Map.ProtoReflect.Descriptor instead.
func (*StringInt32Map) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *StringInt32Map) GetValues() map[string]int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type StringFloat32Map struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]float32     `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringFloat32Map) Reset() {
	*x = StringFloat32Map{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringFloat32Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringFloat32Map) ProtoMessage() {}

func (x *StringFloat32Map) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringFloat32Map.ProtoReflect.Descriptor instead.
func (*StringFloat32Map) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *StringFloat32Map) GetValues() map[string]float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type FloatDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distribution  *StringFloat32Map      `protobuf:"bytes,1,opt,name=distribution,proto3" json:"distribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatDistribution) Reset() {
	*x = FloatDistribution{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatDistribution) ProtoMessage() {}

func (x *FloatDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatDistribution.ProtoReflect.Descriptor instead.
func (*FloatDistribution) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *FloatDistribution) GetDistribution() *StringFloat32Map {
	if x != nil {
		return x.Distribution
	}
	return nil
}

type CongestionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timerange     string                 `protobuf:"bytes,1,opt,name=timerange,proto3" json:"timerange,omitempty"`
	Pairing       *StringInt32Map        `protobuf:"bytes,2,opt,name=pairing,proto3" json:"pairing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CongestionEntry) Reset() {
	*x = CongestionEntry{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CongestionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CongestionEntry) ProtoMessage() {}

func (x *CongestionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CongestionEntry.ProtoReflect.Descriptor instead.
func (*CongestionEntry) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *CongestionEntry) GetTimerange() string {
	if x != nil {
		return x.Timerange
	}
	return ""
}

func (x *CongestionEntry) GetPairing() *StringInt32Map {
	if x != nil {
		return x.Pairing
	}
	return nil
}

type Distribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distribution  *StringInt32Map        `protobuf:"bytes,1,opt,name=distribution,proto3" json:"distribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution) Reset() {
	*x = Distribution{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution) ProtoMessage() {}

func (x *Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution.ProtoReflect.Descriptor instead.
func (*Distribution) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *Distribution) GetDistribution() *StringInt32Map {
	if x != nil {
		return x.Distribution
	}
	return nil
}

type Congestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*CongestionEntry     `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Congestion) Reset() {
	*x = Congestion{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Congestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Congestion) ProtoMessage() {}

func (x *Congestion) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Congestion.ProtoReflect.Descriptor instead.
func (*Congestion) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *Congestion) GetValues() []*CongestionEntry {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\n" +
	"metricraft\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\ttimeframe\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\x05R\n" +
	"resolution\"\x8b\x01\n" +
	"\x0eStringInt32Map\x12>\n" +
	"\x06values\x18\x01 \x03(\v2&.metricraft.StringInt32Map.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x8f\x01\n" +
	"\x10StringFloat32Map\x12@\n" +
	"\x06values\x18\x01 \x03(\v2(.metricraft.StringFloat32Map.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"U\n" +
	"\x11floatDistribution\x12@\n" +
	"\fdistribution\x18\x01 \x01(\v2\x1c.metricraft.StringFloat32MapR\fdistribution\"e\n" +
	"\x0fCongestionEntry\x12\x1c\n" +
	"\ttimerange\x18\x01 \x01(\tR\ttimerange\x124\n" +
	"\apairing\x18\x02 \x01(\v2\x1a.metricraft.StringInt32MapR\apairing\"N\n" +
	"\fdistribution\x12>\n" +
	"\fdistribution\x18\x01 \x01(\v2\x1a.metricraft.StringInt32MapR\fdistribution\"A\n" +
	"\n" +
	"congestion\x123\n" +
	"\x06values\x18\x01 \x03(\v2\x1b.metricraft.CongestionEntryR\x06values2\xa8\x02\n" +
	"\n" +
	"Metricraft\x12I\n" +
	"\x16getGeographicalTraffic\x12\x15.metricraft.timeframe\x1a\x18.metricraft.distribution\x12E\n" +
	"\x14getTrafficCongestion\x12\x15.metricraft.timeframe\x1a\x16.metricraft.congestion\x12@\n" +
	"\rgetP95Latency\x12\x15.metricraft.timeframe\x1a\x18.metricraft.distribution\x12F\n" +
	"\x0egetUptimeScore\x12\x15.metricraft.timeframe\x1a\x1d.metricraft.floatDistributionB\x12Z\x10metricraft/protob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_proto_goTypes = []any{
	(*Timeframe)(nil),             // 0: metricraft.timeframe
	(*StringInt32Map)(nil),        // 1: metricraft.StringInt32Map
	(*StringFloat32Map)(nil),      // 2: metricraft.StringFloat32Map
	(*FloatDistribution)(nil),     // 3: metricraft.floatDistribution
	(*CongestionEntry)(nil),       // 4: metricraft.CongestionEntry
	(*Distribution)(nil),          // 5: metricraft.distribution
	(*Congestion)(nil),            // 6: metricraft.congestion
	nil,                           // 7: metricraft.StringInt32Map.ValuesEntry
	nil,                           // 8: metricraft.StringFloat32Map.ValuesEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	9,  // 0: metricraft.timeframe.start:type_name -> google.protobuf.Timestamp
	7,  // 1: metricraft.StringInt32Map.values:type_name -> metricraft.StringInt32Map.ValuesEntry
	8,  // 2: metricraft.StringFloat32Map.values:type_name -> metricraft.StringFloat32Map.ValuesEntry
	2,  // 3: metricraft.floatDistribution.distribution:type_name -> metricraft.StringFloat32Map
	1,  // 4: metricraft.CongestionEntry.pairing:type_name -> metricraft.StringInt32Map
	1,  // 5: metricraft.distribution.distribution:type_name -> metricraft.StringInt32Map
	4,  // 6: metricraft.congestion.values:type_name -> metricraft.CongestionEntry
	0,  // 7: metricraft.Metricraft.getGeographicalTraffic:input_type -> metricraft.timeframe
	0,  // 8: metricraft.Metricraft.getTrafficCongestion:input_type -> metricraft.timeframe
	0,  // 9: metricraft.Metricraft.getP95Latency:input_type -> metricraft.timeframe
	0,  // 10: metricraft.Metricraft.getUptimeScore:input_type -> metricraft.timeframe
	5,  // 11: metricraft.Metricraft.getGeographicalTraffic:output_type -> metricraft.distribution
	6,  // 12: metricraft.Metricraft.getTrafficCongestion:output_type -> metricraft.congestion
	5,  // 13: metricraft.Metricraft.getP95Latency:output_type -> metricraft.distribution
	3,  // 14: metricraft.Metricraft.getUptimeScore:output_type -> metricraft.floatDistribution
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
