// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timeframe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeframe     *durationpb.Duration   `protobuf:"bytes,1,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timeframe) Reset() {
	*x = Timeframe{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timeframe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeframe) ProtoMessage() {}

func (x *Timeframe) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeframe.ProtoReflect.Descriptor instead.
func (*Timeframe) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Timeframe) GetTimeframe() *durationpb.Duration {
	if x != nil {
		return x.Timeframe
	}
	return nil
}

type Congestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Congestion    map[string]int32       `protobuf:"bytes,1,rep,name=congestion,proto3" json:"congestion,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Congestion) Reset() {
	*x = Congestion{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Congestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Congestion) ProtoMessage() {}

func (x *Congestion) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Congestion.ProtoReflect.Descriptor instead.
func (*Congestion) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Congestion) GetCongestion() map[string]int32 {
	if x != nil {
		return x.Congestion
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\n" +
	"metricraft\x1a\x1egoogle/protobuf/duration.proto\"D\n" +
	"\ttimeframe\x127\n" +
	"\ttimeframe\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\ttimeframe\"\x93\x01\n" +
	"\n" +
	"congestion\x12F\n" +
	"\n" +
	"congestion\x18\x01 \x03(\v2&.metricraft.congestion.CongestionEntryR\n" +
	"congestion\x1a=\n" +
	"\x0fCongestionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012O\n" +
	"\n" +
	"Metricraft\x12A\n" +
	"\x10getUrlCongestion\x12\x15.metricraft.timeframe\x1a\x16.metricraft.congestionB\x12Z\x10metricraft/protob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(*Timeframe)(nil),           // 0: metricraft.timeframe
	(*Congestion)(nil),          // 1: metricraft.congestion
	nil,                         // 2: metricraft.congestion.CongestionEntry
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_service_proto_depIdxs = []int32{
	3, // 0: metricraft.timeframe.timeframe:type_name -> google.protobuf.Duration
	2, // 1: metricraft.congestion.congestion:type_name -> metricraft.congestion.CongestionEntry
	0, // 2: metricraft.Metricraft.getUrlCongestion:input_type -> metricraft.timeframe
	1, // 3: metricraft.Metricraft.getUrlCongestion:output_type -> metricraft.congestion
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
