// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Metricraft_GetGeographicalTraffic_FullMethodName = "/metricraft.Metricraft/getGeographicalTraffic"
	Metricraft_GetTrafficCongestion_FullMethodName   = "/metricraft.Metricraft/getTrafficCongestion"
	Metricraft_GetP95Latency_FullMethodName          = "/metricraft.Metricraft/getP95Latency"
)

// MetricraftClient is the client API for Metricraft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricraftClient interface {
	GetGeographicalTraffic(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error)
	GetTrafficCongestion(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Congestion, error)
	GetP95Latency(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error)
}

type metricraftClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricraftClient(cc grpc.ClientConnInterface) MetricraftClient {
	return &metricraftClient{cc}
}

func (c *metricraftClient) GetGeographicalTraffic(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Distribution)
	err := c.cc.Invoke(ctx, Metricraft_GetGeographicalTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetTrafficCongestion(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Congestion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Congestion)
	err := c.cc.Invoke(ctx, Metricraft_GetTrafficCongestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetP95Latency(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Distribution)
	err := c.cc.Invoke(ctx, Metricraft_GetP95Latency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricraftServer is the server API for Metricraft service.
// All implementations must embed UnimplementedMetricraftServer
// for forward compatibility.
type MetricraftServer interface {
	GetGeographicalTraffic(context.Context, *Timeframe) (*Distribution, error)
	GetTrafficCongestion(context.Context, *Timeframe) (*Congestion, error)
	GetP95Latency(context.Context, *Timeframe) (*Distribution, error)
	mustEmbedUnimplementedMetricraftServer()
}

// UnimplementedMetricraftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricraftServer struct{}

func (UnimplementedMetricraftServer) GetGeographicalTraffic(context.Context, *Timeframe) (*Distribution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGeographicalTraffic not implemented")
}
func (UnimplementedMetricraftServer) GetTrafficCongestion(context.Context, *Timeframe) (*Congestion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrafficCongestion not implemented")
}
func (UnimplementedMetricraftServer) GetP95Latency(context.Context, *Timeframe) (*Distribution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetP95Latency not implemented")
}
func (UnimplementedMetricraftServer) mustEmbedUnimplementedMetricraftServer() {}
func (UnimplementedMetricraftServer) testEmbeddedByValue()                    {}

// UnsafeMetricraftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricraftServer will
// result in compilation errors.
type UnsafeMetricraftServer interface {
	mustEmbedUnimplementedMetricraftServer()
}

func RegisterMetricraftServer(s grpc.ServiceRegistrar, srv MetricraftServer) {
	// If the following call panics, it indicates UnimplementedMetricraftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Metricraft_ServiceDesc, srv)
}

func _Metricraft_GetGeographicalTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetGeographicalTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetGeographicalTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetGeographicalTraffic(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetTrafficCongestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetTrafficCongestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetTrafficCongestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetTrafficCongestion(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetP95Latency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetP95Latency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetP95Latency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetP95Latency(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

// Metricraft_ServiceDesc is the grpc.ServiceDesc for Metricraft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metricraft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metricraft.Metricraft",
	HandlerType: (*MetricraftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getGeographicalTraffic",
			Handler:    _Metricraft_GetGeographicalTraffic_Handler,
		},
		{
			MethodName: "getTrafficCongestion",
			Handler:    _Metricraft_GetTrafficCongestion_Handler,
		},
		{
			MethodName: "getP95Latency",
			Handler:    _Metricraft_GetP95Latency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
