// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Metricraft_GetGeographicalTraffic_FullMethodName     = "/metricraft.Metricraft/getGeographicalTraffic"
	Metricraft_GetTrafficCongestion_FullMethodName       = "/metricraft.Metricraft/getTrafficCongestion"
	Metricraft_GetP95Latency_FullMethodName              = "/metricraft.Metricraft/getP95Latency"
	Metricraft_GetUptimeScore_FullMethodName             = "/metricraft.Metricraft/getUptimeScore"
	Metricraft_GetThroughput_FullMethodName              = "/metricraft.Metricraft/getThroughput"
	Metricraft_GetGeographicalPerformance_FullMethodName = "/metricraft.Metricraft/getGeographicalPerformance"
	Metricraft_GetStatusCodeDistribution_FullMethodName  = "/metricraft.Metricraft/getStatusCodeDistribution"
	Metricraft_GetRouteCongestion_FullMethodName         = "/metricraft.Metricraft/getRouteCongestion"
	Metricraft_GetHttpMethodDistribution_FullMethodName  = "/metricraft.Metricraft/getHttpMethodDistribution"
	Metricraft_GetUniqueVisitors_FullMethodName          = "/metricraft.Metricraft/getUniqueVisitors"
	Metricraft_GetHotHours_FullMethodName                = "/metricraft.Metricraft/getHotHours"
	Metricraft_CreateWorker_FullMethodName               = "/metricraft.Metricraft/createWorker"
	Metricraft_DeleteWorker_FullMethodName               = "/metricraft.Metricraft/deleteWorker"
	Metricraft_UpdateWorker_FullMethodName               = "/metricraft.Metricraft/updateWorker"
	Metricraft_GetWorkerUptime_FullMethodName            = "/metricraft.Metricraft/getWorkerUptime"
)

// MetricraftClient is the client API for Metricraft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricraftClient interface {
	GetGeographicalTraffic(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error)
	GetTrafficCongestion(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Congestion, error)
	GetP95Latency(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error)
	GetUptimeScore(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*FloatDistribution, error)
	GetThroughput(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Throughput, error)
	GetGeographicalPerformance(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*FloatDistribution, error)
	GetStatusCodeDistribution(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error)
	GetRouteCongestion(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error)
	GetHttpMethodDistribution(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Congestion, error)
	GetUniqueVisitors(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*SimpleRepeatedDistribution, error)
	GetHotHours(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*SimpleRepeatedDistribution, error)
	CreateWorker(ctx context.Context, in *Worker, opts ...grpc.CallOption) (*Status, error)
	DeleteWorker(ctx context.Context, in *WorkerUrl, opts ...grpc.CallOption) (*Status, error)
	UpdateWorker(ctx context.Context, in *Worker, opts ...grpc.CallOption) (*Status, error)
	GetWorkerUptime(ctx context.Context, in *WorkerUrl, opts ...grpc.CallOption) (*WorkerUptime, error)
}

type metricraftClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricraftClient(cc grpc.ClientConnInterface) MetricraftClient {
	return &metricraftClient{cc}
}

func (c *metricraftClient) GetGeographicalTraffic(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Distribution)
	err := c.cc.Invoke(ctx, Metricraft_GetGeographicalTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetTrafficCongestion(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Congestion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Congestion)
	err := c.cc.Invoke(ctx, Metricraft_GetTrafficCongestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetP95Latency(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Distribution)
	err := c.cc.Invoke(ctx, Metricraft_GetP95Latency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetUptimeScore(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*FloatDistribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FloatDistribution)
	err := c.cc.Invoke(ctx, Metricraft_GetUptimeScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetThroughput(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Throughput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Throughput)
	err := c.cc.Invoke(ctx, Metricraft_GetThroughput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetGeographicalPerformance(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*FloatDistribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FloatDistribution)
	err := c.cc.Invoke(ctx, Metricraft_GetGeographicalPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetStatusCodeDistribution(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Distribution)
	err := c.cc.Invoke(ctx, Metricraft_GetStatusCodeDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetRouteCongestion(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Distribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Distribution)
	err := c.cc.Invoke(ctx, Metricraft_GetRouteCongestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetHttpMethodDistribution(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*Congestion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Congestion)
	err := c.cc.Invoke(ctx, Metricraft_GetHttpMethodDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetUniqueVisitors(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*SimpleRepeatedDistribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleRepeatedDistribution)
	err := c.cc.Invoke(ctx, Metricraft_GetUniqueVisitors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetHotHours(ctx context.Context, in *Timeframe, opts ...grpc.CallOption) (*SimpleRepeatedDistribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleRepeatedDistribution)
	err := c.cc.Invoke(ctx, Metricraft_GetHotHours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) CreateWorker(ctx context.Context, in *Worker, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Metricraft_CreateWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) DeleteWorker(ctx context.Context, in *WorkerUrl, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Metricraft_DeleteWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) UpdateWorker(ctx context.Context, in *Worker, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Metricraft_UpdateWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricraftClient) GetWorkerUptime(ctx context.Context, in *WorkerUrl, opts ...grpc.CallOption) (*WorkerUptime, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerUptime)
	err := c.cc.Invoke(ctx, Metricraft_GetWorkerUptime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricraftServer is the server API for Metricraft service.
// All implementations must embed UnimplementedMetricraftServer
// for forward compatibility.
type MetricraftServer interface {
	GetGeographicalTraffic(context.Context, *Timeframe) (*Distribution, error)
	GetTrafficCongestion(context.Context, *Timeframe) (*Congestion, error)
	GetP95Latency(context.Context, *Timeframe) (*Distribution, error)
	GetUptimeScore(context.Context, *Timeframe) (*FloatDistribution, error)
	GetThroughput(context.Context, *Timeframe) (*Throughput, error)
	GetGeographicalPerformance(context.Context, *Timeframe) (*FloatDistribution, error)
	GetStatusCodeDistribution(context.Context, *Timeframe) (*Distribution, error)
	GetRouteCongestion(context.Context, *Timeframe) (*Distribution, error)
	GetHttpMethodDistribution(context.Context, *Timeframe) (*Congestion, error)
	GetUniqueVisitors(context.Context, *Timeframe) (*SimpleRepeatedDistribution, error)
	GetHotHours(context.Context, *Timeframe) (*SimpleRepeatedDistribution, error)
	CreateWorker(context.Context, *Worker) (*Status, error)
	DeleteWorker(context.Context, *WorkerUrl) (*Status, error)
	UpdateWorker(context.Context, *Worker) (*Status, error)
	GetWorkerUptime(context.Context, *WorkerUrl) (*WorkerUptime, error)
	mustEmbedUnimplementedMetricraftServer()
}

// UnimplementedMetricraftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricraftServer struct{}

func (UnimplementedMetricraftServer) GetGeographicalTraffic(context.Context, *Timeframe) (*Distribution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGeographicalTraffic not implemented")
}
func (UnimplementedMetricraftServer) GetTrafficCongestion(context.Context, *Timeframe) (*Congestion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrafficCongestion not implemented")
}
func (UnimplementedMetricraftServer) GetP95Latency(context.Context, *Timeframe) (*Distribution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetP95Latency not implemented")
}
func (UnimplementedMetricraftServer) GetUptimeScore(context.Context, *Timeframe) (*FloatDistribution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUptimeScore not implemented")
}
func (UnimplementedMetricraftServer) GetThroughput(context.Context, *Timeframe) (*Throughput, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThroughput not implemented")
}
func (UnimplementedMetricraftServer) GetGeographicalPerformance(context.Context, *Timeframe) (*FloatDistribution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGeographicalPerformance not implemented")
}
func (UnimplementedMetricraftServer) GetStatusCodeDistribution(context.Context, *Timeframe) (*Distribution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatusCodeDistribution not implemented")
}
func (UnimplementedMetricraftServer) GetRouteCongestion(context.Context, *Timeframe) (*Distribution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRouteCongestion not implemented")
}
func (UnimplementedMetricraftServer) GetHttpMethodDistribution(context.Context, *Timeframe) (*Congestion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHttpMethodDistribution not implemented")
}
func (UnimplementedMetricraftServer) GetUniqueVisitors(context.Context, *Timeframe) (*SimpleRepeatedDistribution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniqueVisitors not implemented")
}
func (UnimplementedMetricraftServer) GetHotHours(context.Context, *Timeframe) (*SimpleRepeatedDistribution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHotHours not implemented")
}
func (UnimplementedMetricraftServer) CreateWorker(context.Context, *Worker) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorker not implemented")
}
func (UnimplementedMetricraftServer) DeleteWorker(context.Context, *WorkerUrl) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorker not implemented")
}
func (UnimplementedMetricraftServer) UpdateWorker(context.Context, *Worker) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorker not implemented")
}
func (UnimplementedMetricraftServer) GetWorkerUptime(context.Context, *WorkerUrl) (*WorkerUptime, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkerUptime not implemented")
}
func (UnimplementedMetricraftServer) mustEmbedUnimplementedMetricraftServer() {}
func (UnimplementedMetricraftServer) testEmbeddedByValue()                    {}

// UnsafeMetricraftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricraftServer will
// result in compilation errors.
type UnsafeMetricraftServer interface {
	mustEmbedUnimplementedMetricraftServer()
}

func RegisterMetricraftServer(s grpc.ServiceRegistrar, srv MetricraftServer) {
	// If the following call panics, it indicates UnimplementedMetricraftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Metricraft_ServiceDesc, srv)
}

func _Metricraft_GetGeographicalTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetGeographicalTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetGeographicalTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetGeographicalTraffic(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetTrafficCongestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetTrafficCongestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetTrafficCongestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetTrafficCongestion(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetP95Latency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetP95Latency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetP95Latency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetP95Latency(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetUptimeScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetUptimeScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetUptimeScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetUptimeScore(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetThroughput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetThroughput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetThroughput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetThroughput(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetGeographicalPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetGeographicalPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetGeographicalPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetGeographicalPerformance(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetStatusCodeDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetStatusCodeDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetStatusCodeDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetStatusCodeDistribution(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetRouteCongestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetRouteCongestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetRouteCongestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetRouteCongestion(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetHttpMethodDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetHttpMethodDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetHttpMethodDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetHttpMethodDistribution(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetUniqueVisitors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetUniqueVisitors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetUniqueVisitors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetUniqueVisitors(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetHotHours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeframe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetHotHours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetHotHours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetHotHours(ctx, req.(*Timeframe))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_CreateWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Worker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).CreateWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_CreateWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).CreateWorker(ctx, req.(*Worker))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_DeleteWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerUrl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).DeleteWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_DeleteWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).DeleteWorker(ctx, req.(*WorkerUrl))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_UpdateWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Worker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).UpdateWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_UpdateWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).UpdateWorker(ctx, req.(*Worker))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metricraft_GetWorkerUptime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerUrl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricraftServer).GetWorkerUptime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metricraft_GetWorkerUptime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricraftServer).GetWorkerUptime(ctx, req.(*WorkerUrl))
	}
	return interceptor(ctx, in, info, handler)
}

// Metricraft_ServiceDesc is the grpc.ServiceDesc for Metricraft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metricraft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metricraft.Metricraft",
	HandlerType: (*MetricraftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getGeographicalTraffic",
			Handler:    _Metricraft_GetGeographicalTraffic_Handler,
		},
		{
			MethodName: "getTrafficCongestion",
			Handler:    _Metricraft_GetTrafficCongestion_Handler,
		},
		{
			MethodName: "getP95Latency",
			Handler:    _Metricraft_GetP95Latency_Handler,
		},
		{
			MethodName: "getUptimeScore",
			Handler:    _Metricraft_GetUptimeScore_Handler,
		},
		{
			MethodName: "getThroughput",
			Handler:    _Metricraft_GetThroughput_Handler,
		},
		{
			MethodName: "getGeographicalPerformance",
			Handler:    _Metricraft_GetGeographicalPerformance_Handler,
		},
		{
			MethodName: "getStatusCodeDistribution",
			Handler:    _Metricraft_GetStatusCodeDistribution_Handler,
		},
		{
			MethodName: "getRouteCongestion",
			Handler:    _Metricraft_GetRouteCongestion_Handler,
		},
		{
			MethodName: "getHttpMethodDistribution",
			Handler:    _Metricraft_GetHttpMethodDistribution_Handler,
		},
		{
			MethodName: "getUniqueVisitors",
			Handler:    _Metricraft_GetUniqueVisitors_Handler,
		},
		{
			MethodName: "getHotHours",
			Handler:    _Metricraft_GetHotHours_Handler,
		},
		{
			MethodName: "createWorker",
			Handler:    _Metricraft_CreateWorker_Handler,
		},
		{
			MethodName: "deleteWorker",
			Handler:    _Metricraft_DeleteWorker_Handler,
		},
		{
			MethodName: "updateWorker",
			Handler:    _Metricraft_UpdateWorker_Handler,
		},
		{
			MethodName: "getWorkerUptime",
			Handler:    _Metricraft_GetWorkerUptime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
