syntax = "proto3";
package metricraft;
option go_package = "metricraft/proto";
import "google/protobuf/timestamp.proto";


service Metricraft {
  rpc getGeographicalTraffic(timeframe) returns (distribution);
  rpc getTrafficCongestion(timeframe) returns (congestion);
  rpc getP95Latency(timeframe) returns (distribution);
  rpc getUptimeScore(timeframe) returns (floatDistribution);
  rpc getThroughput(timeframe) returns (throughput);
  rpc getGeographicalPerformance(timeframe) returns (floatDistribution);
  rpc getStatusCodeDistribution(timeframe) returns (distribution);
  rpc getRouteCongestion(timeframe) returns (distribution);
  rpc getHttpMethodDistribution(timeframe) returns (congestion);
  rpc getUniqueVisitors(timeframe) returns (simpleRepeatedDistribution);

  rpc createWorker(worker) returns (status);
  rpc deleteWorker(workerUrl) returns (status);
  rpc updateWorker(worker) returns (status);
  rpc getWorkerUptime(workerUrl) returns (workerUptime);
}

message simpleRepeatedDistribution {
  repeated StringInt32Map distribution = 1;
}

message timeframe{
  google.protobuf.Timestamp start = 1;
  int32 resolution = 2;
  string timezone = 3;
}

message workerUrl{
  string url = 1;
  string timezone = 2;
  int32 pollInterval = 3;
}

message worker{
  string url = 1;
  int32 pollInterval = 2;
  map<string, string> headers = 3;
  string appName = 4;
}

message status{
  bool success = 1;
  string err = 2;
  int32 statusCode = 3;
}

message workerUptime{
  repeated workerUptimeEntry entries = 1;
}

message workerUptimeEntry{
  google.protobuf.Timestamp stamp = 1;
  int32 status = 2;
}

message StringInt32Map {
  map<string, int32> values = 1;
}

message StringFloat32Map {
  map<string, float> values = 1;
}

message floatDistribution {
  StringFloat32Map distribution = 1;
}

message throughput {
  repeated ThroughputEntry values = 1;
  float computedThroughput = 2;
  int32 uniqUsers = 3;
}

message ThroughputEntry{
  string timerange = 1;
  int32 value = 2;
}

message CongestionEntry {
  string timerange = 1;
  StringInt32Map pairing = 2;
}

message distribution{
  StringInt32Map distribution = 1;
}

message congestion {
  repeated CongestionEntry values = 1;
}
