name: Go
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      uses: actions/setup-go@v5
      with:
        go-version: ^1.26.x
    - name: Build
      run: cd worker/cmd && go build .
    - name: Test
      run: |
        cd worker/enter && go test -v .
        cd ../external && go test -v .
